name: NodeJS with Webpack

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ pages ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set BASE_URL
      id: base_url
      run: |
        if [[ $GITHUB_REPOSITORY == "seal-pavel/halloween.veganrussian.ru" ]]; then
          echo "::set-output name=BASE_URL::https://seal-pavel.github.io/halloween.veganrussian.ru/"
        else
          echo "::set-output name=BASE_URL::'test'
        fi

    - name: Build
      run: |
        npm install
        BASE_URL=${{ steps.base_url.outputs.BASE_URL }} npx webpack
    - name: Deploy ðŸš€
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: pages # The branch the action should deploy to.
        folder: dist
